name = "metapi-cloudflare"
main = "src/cloudflare/worker.ts"
compatibility_date = "2026-05-28"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/web"
binding = "ASSETS"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "METAPI_DB"
database_name = "metapi"
database_id = "12f3fa4a-c016-40f2-86c9-cf00d076f79e"

[[r2_buckets]]
binding = "METAPI_FILES"
bucket_name = "metapi-files"

[triggers]
crons = []

[observability]
enabled = true
